# This rule is not used by the project kratos-staticclient itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over operator.opertor.kratos.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kratos-staticclient
    app.kubernetes.io/managed-by: kustomize
  name: kratos-admin-role
rules:
- apiGroups:
  - operator.opertor.kratos.io
  resources:
  - kratos
  verbs:
  - '*'
- apiGroups:
  - operator.opertor.kratos.io
  resources:
  - kratos/status
  verbs:
  - get
