---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.opertor.kratos.io
  resources:
  - kratos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.opertor.kratos.io
  resources:
  - kratos/finalizers
  verbs:
  - update
- apiGroups:
  - operator.opertor.kratos.io
  resources:
  - kratos/status
  verbs:
  - get
  - patch
  - update
